# unidbg-fetch-qsign 运行路径 (可填写相对于 mirai 运行目录的路径，或者绝对路径)
base-path: 'txlib/8.9.90'
# 忽略环境为 Termux，强制加载签名服务
# 部分人可以在 Termux 中使用，部分人无法通过 Termux 使用
# 如果你执意要在 Termux 中使用本插件，请开启本选项
ignore-termux: false
app_install_folder: '/data/app/~~nNzv5koU9DgkrbtCpa02wQ==/${packageName}-fR9VqAFGIZNVZ8MgZYh0Ow=='
screen_size_width: 1080
screen_size_height: 2400
density: 2.75
# /sys/devices/soc0/serial_number
serial_number: 0x0000043be8571339
android_version: 13
android_sdk_version: 33
target_sdk_version: 29
storage_size: 137438953471